services:
  postgres:
    image: pgvector/pgvector:pg17
    container_name: rag-postgres
    restart: unless-stopped

    environment:
      POSTGRES_DB: ragdb
      POSTGRES_USER: raguser
      POSTGRES_PASSWORD: ragpassword

    ports:
      - "5433:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U raguser -d ragdb"]
      interval: 5s
      timeout: 5s
      retries: 5


  redis:
    image: redis:7-alpine
    container_name: rag-redis
    restart: unless-stopped

    ports:
      - "6379:6379"

    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5


  api:
    build: .
    container_name: rag-api
    restart: unless-stopped

    command:
      [
        "uvicorn",
        "app.main:app",
        "--host",
        "0.0.0.0",
        "--port",
        "8000"
      ]

    ports:
      - "8000:8000"

    volumes:
      - uploads_data:/app/data/uploads

    environment:
      DATABASE_URL: postgresql+psycopg://raguser:ragpassword@postgres:5432/ragdb
      REDIS_HOST: redis
      REDIS_PORT: 6379
      OPENROUTER_API_KEY: ${OPENROUTER_API_KEY}

    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy


  worker:
    build: .
    container_name: rag-worker
    restart: unless-stopped

    command:
      [
        "python",
        "-m",
        "app.worker.ingestion_worker"
      ]

    volumes:
      - uploads_data:/app/data/uploads

    environment:
      DATABASE_URL: postgresql+psycopg://raguser:ragpassword@postgres:5432/ragdb
      REDIS_HOST: redis
      REDIS_PORT: 6379
      OPENROUTER_API_KEY: ${OPENROUTER_API_KEY}

    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy


volumes:
  postgres_data:
  uploads_data: